enableGitInfo = true
theme = "minimo"
baseURL = "http://www.soebes.de"
# disablePathToLower = false
languageCode = "en-us"
#title = "SoftwareEntwicklung Beratung Schulung"
#title = "SoEBeS"
uglyURLs = true 
googleAnalytics = ""
logo = "/images/weglogo.gif"  
[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.sidebar]
enable = true

[params.comments]
enable = false
# number of blog posts displayed in each page
#paginate = 6

[[menu.main]]
name = "Repo"
weight = -10
identifier = "repository"
url = "https://github.com/MunifTanjim/minimo"

